version: "3.6"
services:
  mqtt:
    image: eclipse-mosquitto
    restart: unless-stopped
    networks:
      - mqtt
    volumes:
    - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  kamstrup:
    image: collinit/kamstrup:0.0.1
    restart: unless-stopped
    networks:
      - mqtt
 #   devices:
 #     - /dev/ttyUSB1:/dev/ttyUSB1
   

networks:
  mqtt:
